[dependencies]
base = "0.13.4"
icrc1 = "0.0.2"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main"
StableBuffer = "https://github.com/canscale/StableBuffer#v0.2.0"
itertools = "0.1.2"
